# Generated by Django 4.1.4 on 2022-12-28 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseproject', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='developer',
            old_name='category',
            new_name='sex',
        ),
    ]
