# Generated by Django 4.1.4 on 2022-12-28 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseproject', '0002_rename_category_developer_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='bio',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='developer',
            name='bio',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
